#!/bin/sh

nixos-generate-config --root /mnt
git config --global user.name "install-bot"
git config --global user.email "install-bot@users.noreply"
git add .
git commit -am "bot add"

nixos-install --root /mnt --flake '/mnt/etc/nixos#nixos-desktop' --impure
