#!/bin/sh

# run right after partitioning

nixos-generate-config --root /mnt
git config --global user.name "bot"
git config --global user.email "bot"
git add .
git commit -am "generate config"

# impure or it will complain some path is missing
nixos-install --root /mnt --flake '/mnt/etc/nixos#nixos-desktop' --impure
