#!/bin/sh

# run right after partitioning

nixos-generate-config --root /mnt

# impure or it will complain some path is missing
nixos-install --root /mnt --flake '/mnt/etc/nixos#nixos-desktop' --impure
